import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.KOLBO_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())

// Kolbo.AI override: strip upstream opencode providers and inject our slim
// Kolbo provider pointing at kolbo-api. Usage is billed against the user's
// Kolbo.AI credit balance via the hidden kodu-default model in kolbo-api.
// (Internal DB identifier stays "kodu-default"; public-facing id is "kolbo-default".)
const snapshot = JSON.parse(modelsData) as Record<string, any>
delete snapshot.opencode
delete snapshot["opencode-go"]
delete snapshot.kodu
snapshot.kolbo = {
  id: "kolbo",
  env: ["KOLBO_API_KEY"],
  npm: "@ai-sdk/openai-compatible",
  api: "https://api.kolbo.ai/api/kolbo/v1",
  name: "Kolbo",
  doc: "https://kolbo.ai/cli",
  models: {
    "kolbo-default": {
      id: "kolbo-default",
      name: "Kolbo",
      family: "kolbo",
      attachment: true,
      reasoning: false,
      tool_call: true,
      structured_output: true,
      temperature: true,
      knowledge: "2025-01",
      release_date: "2026-04-10",
      last_updated: "2026-04-10",
      modalities: { input: ["text", "image"], output: ["text"] },
      open_weights: false,
      cost: { input: 0.4, output: 1.6 },
      limit: { context: 1_000_000, output: 32_768 },
    },
  },
}

await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${JSON.stringify(snapshot, null, 2)}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js (with Kolbo.AI provider injected)")
