id = "kodu"
name = "Kodu"
description = "The open source coding agent."
version = "1.4.2"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/kodu"

[agent_servers.kodu]
name = "Kodu"
icon = "./icons/kodu.svg"

[agent_servers.kodu.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/kodu/releases/download/v1.4.2/opencode-darwin-arm64.zip"
cmd = "./kodu"
args = ["acp"]

[agent_servers.kodu.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/kodu/releases/download/v1.4.2/opencode-darwin-x64.zip"
cmd = "./kodu"
args = ["acp"]

[agent_servers.kodu.targets.linux-aarch64]
archive = "https://github.com/anomalyco/kodu/releases/download/v1.4.2/opencode-linux-arm64.tar.gz"
cmd = "./kodu"
args = ["acp"]

[agent_servers.kodu.targets.linux-x86_64]
archive = "https://github.com/anomalyco/kodu/releases/download/v1.4.2/opencode-linux-x64.tar.gz"
cmd = "./kodu"
args = ["acp"]

[agent_servers.kodu.targets.windows-x86_64]
archive = "https://github.com/anomalyco/kodu/releases/download/v1.4.2/opencode-windows-x64.zip"
cmd = "./kodu.exe"
args = ["acp"]
